"""Provenance table for every configured constant (Phase 0.5 / Phase 8).

Parses the ``source:`` annotations out of the YAML configs and renders them as
a console table or a LaTeX ``tabular`` for the paper. The point is that the
paper's parameter table is *generated from the configuration that actually ran*,
so it can never drift from the simulator.

Provenance tags, in descending order of trustworthiness:

``STD-COMPUTED``  computed from a standard's own equations and validated
                  against that standard's published table
``STD``           fixed by a standard, value checked
``DERIVED``       computed from other configured values by a stated formula
``MEAS``          from a published measurement campaign
``STD-UNVERIFIED``/``MEAS-UNVERIFIED``
                  attributable to a named source, but we could not open the
                  primary document to check the number
``ASSUMED``       our modelling choice; must be defended in the text
``INERT``         recorded but read by no computation, so it cannot affect a
                  result (asserted by tests/test_mac.py)
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterator

from common.config import CONFIG_DIR

TAG_ORDER = [
    "STD-COMPUTED", "STD", "DERIVED", "MEAS",
    "STD-UNVERIFIED", "MEAS-UNVERIFIED", "ASSUMED", "INERT", "VERIFY",
]
TAG_RE = re.compile(r"\[([A-Z-]+)\]")
KEY_RE = re.compile(r"^(\s*)([A-Za-z_][A-Za-z0-9_]*):\s*(.*?)\s*$")


def iter_annotations(path: Path) -> Iterator[tuple[str, str, list[str], str]]:
    """Yield ``(key, value, tags, note)`` for each annotated config entry."""
    lines = path.read_text(encoding="utf-8").splitlines()
    last_key: tuple[str, str] | None = None
    for i, line in enumerate(lines):
        m = KEY_RE.match(line)
        if m and not line.lstrip().startswith("#"):
            last_key = (m.group(2), m.group(3))
            continue
        if "source:" not in line or last_key is None:
            continue
        note = [line.split("source:", 1)[1].strip()]
        for nxt in lines[i + 1:]:
            st = nxt.strip()
            if not st.startswith("#") or "source:" in st:
                break
            body = st.lstrip("# ").strip()
            if not body or KEY_RE.match(body):
                break
            note.append(body)
        text = " ".join(note)
        tags = TAG_RE.findall(text)
        clean = TAG_RE.sub("", text).strip().lstrip("-").strip()
        yield last_key[0], last_key[1], tags, clean
        last_key = None


def collect(config_names: tuple[str, ...] = ("phy.yaml", "hazard.yaml", "policies.yaml")):
    rows = []
    for name in config_names:
        path = CONFIG_DIR / name
        if not path.exists():
            continue
        for key, value, tags, note in iter_annotations(path):
            rows.append({"config": name, "key": key, "value": value or "(block)",
                         "tags": tags or ["UNTAGGED"], "note": note})
    return rows


def summarise(rows) -> dict[str, int]:
    counts: dict[str, int] = {}
    for r in rows:
        for t in r["tags"]:
            counts[t] = counts.get(t, 0) + 1
    return counts


def format_console(rows) -> str:
    out = []
    hdr = f"{'config':<16}{'parameter':<30}{'value':<14}{'provenance':<34}"
    out += ["=" * 128, " RESOLVED CONSTANTS AND THEIR PROVENANCE", "=" * 128, hdr, "-" * 128]

    def rank(r):
        best = min((TAG_ORDER.index(t) if t in TAG_ORDER else 99) for t in r["tags"])
        return (best, r["config"], r["key"])

    for r in sorted(rows, key=rank):
        tags = ",".join(r["tags"])
        val = (r["value"][:12] + "..") if len(r["value"]) > 13 else r["value"]
        note = r["note"][:60]
        out.append(f"{r['config']:<16}{r['key']:<30}{val:<14}{tags:<34}")
        if note:
            out.append(f"{'':<60}{note}")
    out.append("=" * 128)

    counts = summarise(rows)
    out.append(" SUMMARY BY PROVENANCE")
    for tag in TAG_ORDER:
        if tag in counts:
            out.append(f"   {tag:<20} {counts[tag]:>3}")
    for tag, n in sorted(counts.items()):
        if tag not in TAG_ORDER:
            out.append(f"   {tag:<20} {n:>3}")
    unverified = sum(counts.get(t, 0) for t in ("STD-UNVERIFIED", "MEAS-UNVERIFIED", "VERIFY"))
    out.append("")
    out.append(f" {unverified} constant(s) remain attributable but unverified against a")
    out.append(" primary document. Of these, the INERT ones cannot affect any result.")
    out.append("=" * 128)
    return "\n".join(out)


def format_latex(rows) -> str:
    esc = lambda s: (s.replace("_", r"\_").replace("%", r"\%")  # noqa: E731
                     .replace("&", r"\&").replace("^", r"\^{}"))
    out = [r"% Generated by analysis/constants_table.py -- do not edit by hand.",
           r"\begin{tabular}{llll}", r"\toprule",
           r"Config & Parameter & Value & Provenance \\", r"\midrule"]
    for r in sorted(rows, key=lambda x: (x["config"], x["key"])):
        out.append(
            f"{esc(r['config'])} & {esc(r['key'])} & {esc(r['value'][:24])} "
            f"& {esc(','.join(r['tags']))} \\\\"
        )
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    import argparse

    ap = argparse.ArgumentParser(description="AI-HARP constants provenance table")
    ap.add_argument("--latex", action="store_true")
    ap.add_argument("--only", nargs="*", default=None, help="filter by provenance tag")
    args = ap.parse_args(argv)

    rows = collect()
    if args.only:
        want = {t.upper() for t in args.only}
        rows = [r for r in rows if want & set(r["tags"])]
    print(format_latex(rows) if args.latex else format_console(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
