"""Phase 8: LaTeX ``tabular`` output, ready to ``\\input``.

Every table is generated from the same results rows the figures use, so the
paper's numbers cannot drift from the simulator. Tables carry mean +/- std over
seeds and significance markers from :mod:`analysis.stats`; no table ever shows
a single-run number.

Two conventions worth stating in the paper:

* A metric that is undefined in some seeds (TIR when nothing was informed) is
  reported with its usable pair count, not silently averaged over survivors.
* Significance markers come from Holm-corrected p-values, and the effect size
  is printed alongside. A star without an effect size invites the reader to
  mistake a 1% difference for a result.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Sequence

import numpy as np

from analysis.metrics import METRIC_DIRECTION, METRICS_VERSION
from common.config import RESULTS_DIR, ensure_dir
from common.logging_utils import get_logger

logger = get_logger("analysis.tables")

TABLE_DIR = RESULTS_DIR / "tables"

#: Display names and formats for the metrics that appear in paper tables.
METRIC_LABELS: dict[str, tuple[str, str]] = {
    "rwcr": ("RWCR", "{:.3f}"),
    "tir_median_s": ("TIR$_{50}$ (s)", "{:.2f}"),
    "tir_p95_s": ("TIR$_{95}$ (s)", "{:.2f}"),
    "tx_per_at_risk_informed": ("Tx / informed", "{:.2f}"),
    "actionable_deadline_miss_rate": ("Miss rate", "{:.3f}"),
    "pdr": ("PDR", "{:.3f}"),
    "collisions_per_delivered": ("Coll./deliv.", "{:.2f}"),
    "transmissions": ("Tx", "{:.0f}"),
}

POLICY_LABELS: dict[str, str] = {
    "ai_harp": r"\textbf{AI-HARP}",
    "flooding": "Flooding",
    "p_persistence_03": "$p$-persistence",
    "p_persistence_05": "$p$-persistence ($p{=}0.5$)",
    "p_persistence_07": "$p$-persistence ($p{=}0.7$)",
    "slotted_1p": "Slotted 1-persistence",
    "weighted_p": "Weighted $p$-persistence",
    "counter_based": "Counter-based",
    "greedy_farthest": "Greedy farthest",
    "dvcast": "DV-CAST",
}


def escape(text: str) -> str:
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("%", r"\%"),
                 ("&", r"\&"), ("#", r"\#")):
        text = text.replace(a, b)
    return text


def _fmt(mu: float, sd: float, fmt: str) -> str:
    if not np.isfinite(mu):
        return "--"
    if not np.isfinite(sd):
        return f"${fmt.format(mu)}$"
    return f"${fmt.format(mu)} \\pm {fmt.format(sd)}$"


def write(text: str, name: str, out_dir: Path | None = None) -> Path:
    out_dir = ensure_dir(out_dir or TABLE_DIR)
    path = out_dir / f"{name}.tex"
    path.write_text(text, encoding="utf-8")
    logger.info("table -> %s", path.name)
    return path


def _header(caption: str) -> list[str]:
    return [
        f"% {caption}",
        f"% Generated by analysis/tables.py (metrics_version={METRICS_VERSION}).",
        "% Do not edit by hand -- regenerate with reproduce.sh.",
    ]


def main_comparison_table(
    df, metrics: Sequence[str], scenario: str, density: float,
    tests: dict[str, Any] | None = None, name: str = "table_main",
) -> Path:
    """The headline per-policy comparison for one cell.

    ``tests`` maps ``policy -> {metric: PairedTest}`` and supplies significance
    markers; the best value per metric is bolded in its own preferred direction.
    """
    sub = df[(df["scenario"] == scenario) & (df["density_veh_km_lane"] == density)]
    policies = [p for p in POLICY_LABELS if p in set(sub["policy"])]

    stats: dict[str, dict[str, tuple[float, float]]] = {}
    for pol in policies:
        d = sub[sub["policy"] == pol]
        stats[pol] = {
            m: (float(d[m].mean()), float(d[m].std()))
            if m in d and np.isfinite(d[m]).any() else (float("nan"), float("nan"))
            for m in metrics
        }

    best: dict[str, str] = {}
    for m in metrics:
        direction = METRIC_DIRECTION.get(m, 1)
        finite = {p: stats[p][m][0] for p in policies if np.isfinite(stats[p][m][0])}
        if finite:
            best[m] = (max if direction > 0 else min)(finite, key=finite.get)

    cols = "l" + "r" * len(metrics)
    lines = _header(f"{scenario}, {density:g} veh/km/lane, "
                    f"{sub['seed'].nunique()} seeds, mean $\\pm$ std")
    lines += [f"\\begin{{tabular}}{{{cols}}}", "\\toprule"]
    lines.append("Scheme & " + " & ".join(
        METRIC_LABELS.get(m, (escape(m), ""))[0] for m in metrics) + r" \\")
    lines.append("\\midrule")

    for pol in policies:
        cells = []
        for m in metrics:
            mu, sd = stats[pol][m]
            txt = _fmt(mu, sd, METRIC_LABELS.get(m, ("", "{:.3f}"))[1])
            if best.get(m) == pol:
                txt = f"\\bfseries {txt}"
            if tests and pol in tests and m in tests[pol]:
                txt += f"$^{{{tests[pol][m].marker}}}$" if tests[pol][m].marker else ""
            cells.append(txt)
        lines.append(f"{POLICY_LABELS.get(pol, escape(pol))} & " + " & ".join(cells) + r" \\")

    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("\n".join(lines), name)


def reference_table(cells, target: float = 0.95, axis: str = "cost",
                    name: str = "table_reference") -> Path:
    """Per-cell oracle-best and best-fixed baseline -- the headline comparator."""
    from analysis.comparator import best_fixed_baseline, per_cell_oracle_best

    oracle = per_cell_oracle_best(cells, target, axis)
    fixed = best_fixed_baseline(cells, target, axis)

    lines = _header(f"Reference points at RWCR $\\geq$ {target:.0%} of each cell's ceiling")
    lines += ["\\begin{tabular}{llrrrr}", "\\toprule",
              r"Scenario & Density & Ceiling & Oracle-best & Fixed-best & Penalty \\",
              "\\midrule"]
    for cell in cells:
        label, o_cost = oracle.per_cell[cell.key]
        f_cost = fixed.cost(cell.key)
        ceil = cell.achievable_quality()
        pen = f_cost / o_cost if np.isfinite(f_cost) and np.isfinite(o_cost) and o_cost else np.nan
        lines.append(
            f"{escape(cell.key.scenario)} & {cell.key.density:g} & "
            f"${ceil:.3f}$ & {POLICY_LABELS.get(label, escape(label))} "
            f"(${o_cost:.2f}$) & ${f_cost:.2f}$ & "
            + (f"${pen:.2f}\\times$" if np.isfinite(pen) else "--") + r" \\"
        )
    lines += ["\\midrule",
              r"\multicolumn{6}{l}{\footnotesize Best single fixed baseline: "
              + POLICY_LABELS.get(fixed.policy, escape(fixed.policy))
              + f" ({escape(fixed.param)}={escape(str(fixed.value))}), "
              + f"mean normalised score {fixed.score:.2f}" + r"} \\",
              "\\bottomrule", "\\end{tabular}"]
    return write("\n".join(lines), name)


def ablation_table(rows: Sequence[dict[str, Any]], metrics: Sequence[str],
                   name: str = "table_ablation") -> Path:
    """Ablations, each as mean +/- std with its delta against the full model."""
    lines = _header("Ablations, 10 seeds each")
    lines += [f"\\begin{{tabular}}{{l{'rr' * len(metrics)}}}", "\\toprule"]
    head = ["Variant"]
    for m in metrics:
        label = METRIC_LABELS.get(m, (escape(m), ""))[0]
        head += [label, r"$\Delta$"]
    lines.append(" & ".join(head) + r" \\")
    lines.append("\\midrule")

    full = next((r for r in rows if r.get("variant") == "full"), None)
    for r in rows:
        cells = [escape(str(r.get("variant", "?")))]
        for m in metrics:
            fmt = METRIC_LABELS.get(m, ("", "{:.3f}"))[1]
            mu, sd = r.get(m, (np.nan, np.nan))
            cells.append(_fmt(mu, sd, fmt))
            if full and m in full and np.isfinite(mu) and np.isfinite(full[m][0]):
                cells.append(f"${mu - full[m][0]:+.3f}$")
            else:
                cells.append("--")
        lines.append(" & ".join(cells) + r" \\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("\n".join(lines), name)


def parameter_table(name: str = "table_parameters") -> Path:
    """PHY/MAC parameters with their provenance tags, straight from the configs.

    Generated from the YAML that actually ran, so the paper's parameter table
    cannot drift from the simulator. The provenance column is the honest part:
    it distinguishes values fixed by a standard from values we chose, and marks
    the ones we could not verify against a primary document.
    """
    from analysis.constants_table import collect

    rows = collect(("phy.yaml",))
    lines = _header("PHY and MAC parameters with provenance")
    lines += ["\\begin{tabular}{llp{0.42\\linewidth}}", "\\toprule",
              r"Parameter & Value & Provenance \\", "\\midrule"]
    for r in sorted(rows, key=lambda x: x["key"]):
        tags = ",".join(r["tags"])
        note = r["note"][:90] + ("..." if len(r["note"]) > 90 else "")
        lines.append(
            f"{escape(r['key'])} & {escape(str(r['value'])[:18])} & "
            f"\\texttt{{{escape(tags)}}} {escape(note)}" + r" \\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("\n".join(lines), name)


def notation_table(name: str = "table_notation") -> Path:
    """Symbols used in the paper, defined once."""
    entries = [
        (r"$\rho(v,h,t)$", "Relevance of hazard $h$ to vehicle $v$ at time $t$"),
        (r"$\rho^{*}(v)$", "Peak relevance of $v$ over the run"),
        (r"$\mathcal{A}$", r"At-risk set, $\{v : \rho^{*}(v) > \theta\}$"),
        (r"$\theta$", "At-risk threshold"),
        (r"$\eta(v,h,t)$", "ETA of $v$ to the hazard span"),
        (r"$\eta_{\mathrm{full}}$", "ETA plateau of the relevance kernel"),
        (r"$\tau_{\eta}$", "ETA decay constant"),
        (r"$\sigma_h(t)$", "Hazard severity under its decay law"),
        (r"$H$", "Oracle lookahead horizon"),
        (r"$R_{\mathrm{nom}}$", "Nominal communication range (median link, at sensitivity)"),
        (r"$n_1, n_2$", "Path-loss exponents below / above the breakpoint"),
        (r"$d_{\mathrm{bp}}$", r"Two-ray breakpoint, $4 h_t h_r / \lambda$"),
        (r"$m$", "Nakagami fading shape parameter"),
        (r"$W$", "Contention window, $\\mathrm{CW_{min}}+1$ slots"),
        (r"$\tau$", "Confidence-gate threshold"),
        (r"$w_1 \ldots w_5$", "Reward weights"),
    ]
    lines = _header("Notation")
    lines += ["\\begin{tabular}{ll}", "\\toprule", r"Symbol & Meaning \\", "\\midrule"]
    lines += [f"{sym} & {desc} \\\\" for sym, desc in entries]
    lines += ["\\bottomrule", "\\end{tabular}"]
    return write("\n".join(lines), name)
